### ISSUE TITLE
Should biotestmine be configured to use cargo? 

### ISSUE THREAD

**Issue by yochannah** [intermine/biotestmine#4]
I'm not sure if this is by design or not, but biotestmine doesn't seem to have the gradle tasks / plugins for cargo set up. This came up in the support chat when someone was trying out the new gradle tutorial and wanted to know if they could launch to a non-embedded tomcat & we referred them to the docs.

https://intermine.readthedocs.io/en/latest/system-requirements/software/gradle/index.html#deploy-a-webapp-cargo

**Comment by julie-sullivan** [comment]
Yes I will add.

This actually was a feature not a bug, I specifically left it out because biotestmine is supposed to be for testing only. But that makes sense that people would expect similar behaviour. I was wrong.

**Comment by julie-sullivan** [comment]
Fixed!
